# Generated by Django 3.2 on 2021-04-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda', models.CharField(max_length=200)),
                ('periodicidade', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('entrada', models.DecimalField(decimal_places=2, max_digits=8)),
                ('maior', models.DecimalField(decimal_places=2, max_digits=8)),
                ('menor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('saida', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
